# 1. Getting started with GEMs and FBA

## Authors
* Sara Benito Vaquerizo, Genome Biology Unit, European Molecular Biology Laboratory (EMBL), Heidelberg
* Francisco Zorrilla, MRC Toxicology Unit, University of Cambridge
* Arianna Basile, MRC Toxicology Unit, University of Cambridge

## Learning outcomes

In this tutorial you will use [cobrapy](https://cobrapy.readthedocs.io/en/latest/) to learn the following:

* **1.1**: Read the models of selected bacterial strains and algae
* **1.2**: Inspect the model - metabolites, reactions and genes
* **1.3**: Run Flux Balance Analysis (FBA) to simulate growth
* **1.4**: Modify medium conditions in your model and assess the differences in growth and production

## Setup

In [1]:
# Import required packages
import cobra
from cobra.io import read_sbml_model, write_sbml_model
from cobra.flux_analysis import (
    single_gene_deletion, 
    single_reaction_deletion, 
    double_gene_deletion,
    double_reaction_deletion
)

## 1.1 Read the models of selected bacterial strains and algae

The [Systems Biology Markup Language](https://sbml.org/) is an XML-based standard format for distributing models which has support for COBRA models through the FBC extension version 3.

Cobrapy has native support for reading and writing SBML with FBCv3. Please note that all id’s in the model must conform to the SBML SID requirements in order to generate a valid SBML file.

All the bacterial models were previously created using CarveMe (https://github.com/cdanielmachado/carveme) and the algae model using CarveMe and PhotoEukStein (https://www.biorxiv.org/content/10.1101/2023.05.22.541783v1)

In [2]:
## Read model
#model_algae=read_sbml_model("/scratch/sbenito/SBV001_Courses/EMBO_MCD2026/Practical_Metabolic_modelling/Data/Chaetoceros_gracilis.xml")
model_halop=read_sbml_model("../Data/Halopseudomonas.xml")
#model_limno=read_sbml_model("/scratch/sbenito/SBV001_Courses/EMBO_MCD2026/Practical_Metabolic_modelling/Data/Limnobacter_thiooxidans.xml")
#model_yoonia=read_sbml_model("/scratch/sbenito/SBV001_Courses/EMBO_MCD2026/Practical_Metabolic_modelling/Data/Yoonia_vestfoldensis.xml")

## 1.2 Inspect the models - metabolites, reactions, genes and compartments

The reactions, metabolites, genes, and compartments attributes of the cobrapy model are a special type of `list` called a `cobra.DictList`, and each one is made up of `cobra.Reaction`, `cobra.Metabolite`, `cobra.Gene`, `cobra.Compartment` objects, respectively.

In [4]:
#Inpect the model composition
print("Reactions: ",len(model_halop.reactions)) #Total number of reactions
print("Metabolites: ",len(model_halop.metabolites))
print("Genes: ", len(model_halop.genes))
print("Compartments: ",len(model_halop.compartments))

Reactions:  2271
Metabolites:  1521
Genes:  1050
Compartments:  3

When using Jupyter notebooks, this type of information is rendered as a table.

In [5]:
model_halop

Just like a regular list, objects in the `DictList` can be retrieved by index. For example, to get the 3rd reaction in the model (we use an index value of 2 because of python's 0-indexing):

In [6]:
model_halop.reactions[50]

We can also check a list of reactions in the model

We will consider the reaction glucose 6-phosphate isomerase, which interconverts glucose 6-phosphate and fructose 6-phosphate. The reaction id for this reaction in our test model is PGI. However, if you want to see the IDs of the first `N` number of reactions in the reconstruction, you can run the code below:

In [8]:
reaction_ids = [reaction.id for reaction in model_halop.reactions]
N = 20
reaction_ids[:N]

['12DGR120tipp',
 '12DGR140tipp',
 '12DGR141tipp',
 '12DGR160tipp',
 '12DGR161tipp',
 '12DGR180tipp',
 '12DGR181tipp',
 '12PPDRtex',
 '12PPDRtpp',
 '13PPDH',
 '1P2CBXLCYCL',
 '1P2CBXLR',
 '1PPDCRc',
 '23CTI1',
 '23CTI2',
 '23CTI3',
 '24DECOAR',
 '25DKGLCNt2rpp',
 '25DKGLCNtex',
 '2AACLPGT161']

We can also inspect one specific reaction to see the thermodynamics (bounds: non-reversible, reversible rection), the reactants, products or genes (GPR; Gene 
protein reaction rule). 
For example, let's inspect the reaction Glucose-6-phosphate isomerase 'PGI'

In [9]:
pgi = model_halop.reactions.get_by_id("PGI")
pgi

We can view the full name, the reaction catalyzed, the bounds and the genes as strings.

In [10]:
print(pgi.name)
print(pgi.reaction)
print(pgi.bounds)
print(pgi.genes)

Glucose-6-phosphate isomerase
g6p_c <=> f6p_c
(-1000.0, 1000.0)
frozenset({<Gene FOUD01000020_1_13 at 0x7e230682b9b0>})

The thermodynamics of a reaction is defined by the upper and lower bounds as large numbers, typically around 1000 are used as infinite limits (unconstrained fluxes). 
Because the `pgi.lower_bound` < 0, and `pgi.upper_bound` > 0, pgi is reversible. Flux can go in one or the other direction.

In [11]:
print(pgi.lower_bound, "< pgi <", pgi.upper_bound)
print(pgi.reversibility)

-1000.0 < pgi < 1000.0
True

The lower and upper bound of reactions can also be modified, and the reversibility attribute will automatically be updated. The preferred method for manipulating bounds is using reaction.bounds, e.g.

In [12]:
# Save original bounds
old_bounds = pgi.bounds

# Define and print new bounds
pgi.bounds = (0, 1000.0) #This indicates a reaction is non-reversible and goes in one specific direction 
print("New bounds: ",pgi.lower_bound, "< pgi <", pgi.upper_bound)
print("Reversibility after modification:", pgi.reversibility)

# Reset bounds and show reversibility
pgi.bounds = old_bounds
print("Reversibility after resetting:", pgi.reversibility)

New bounds:  0 < pgi < 1000.0
Reversibility after modification: False
Reversibility after resetting: True

## 1.3 Run Flux Balance Analysis (FBA) to simulate growth

In the code chunks below we are running FBA as the mathematical framework to simulate growth and compute the metabolic fluxes. First, we need to set an objective function, typically, the biomass reaction. The function `optimize()` will find the solution that maximixes the flux through the biomass synthesis reaction (growth rate) under the specified constraints (medium, reaction bounds, etc).

In [13]:
# Run FBA
print(model_halop.objective)  #Print the reaction set as objective function by default - normally the biomass reaction
model_halop.optimize().objective_value #We maximize the objective function reaction - growth rate (1/h)

# Summary methods help visualizing the flux through the extracellular reactions to see what metabolites are being consumed and produced in the model when we maximize for growth
model_halop.summary()

Maximize
1.0*Growth - 1.0*Growth_reverse_699ae

We can also inspect all reactions that consume or produce a given metabolite in our FBA solution. For example, let't have a look at ATP:

In [14]:
model_halop.metabolites.atp_c.summary()

To inspect the flux of a specific reaction of interest:

In [15]:
model_halop.reactions.PGK.summary()

To inspect fluxes through the first N reactions:

In [16]:
solution = model_halop.optimize()
solution.fluxes[:N]

12DGR120tipp     0.0
12DGR140tipp     0.0
12DGR141tipp     0.0
12DGR160tipp     0.0
12DGR161tipp     0.0
12DGR180tipp     0.0
12DGR181tipp     0.0
12PPDRtex        0.0
12PPDRtpp        0.0
13PPDH           0.0
1P2CBXLCYCL      0.0
1P2CBXLR         0.0
1PPDCRc          0.0
23CTI1           0.0
23CTI2           0.0
23CTI3           0.0
24DECOAR         0.0
25DKGLCNt2rpp    0.0
25DKGLCNtex      0.0
2AACLPGT161      0.0
Name: fluxes, dtype: float64

## 1.4 Modify medium conditions in your model and assess the differences in growth and production

When we used above the summary methods to inspect what are the metabolites being consumed or produced, 'model_halop.summary()', we can observe a very high flux of glucose and other metabolites in the medium. Let's decrease the uptake of glucose in the model and inspect the fluxes again

In [17]:
model_halop.reactions.EX_glc__D_e.bounds = (-20, -10)

print(model_halop.optimize())
print(model_halop.summary())

<Solution 38.797 at 0x7e23051c15b0>
Objective
=========
1.0 Growth = 38.796693605671955

Uptake
------
    Metabolite          Reaction    Flux  C-Number C-Flux
LalaDgluMdap_e EX_LalaDgluMdap_e    3.88        15  0.79%
        abg4_e         EX_abg4_e 0.02595        12  0.00%
         ade_e          EX_ade_e   7.926         5  0.54%
      arg__L_e       EX_arg__L_e   11.48         6  0.94%
         ca2_e          EX_ca2_e  0.2019         0  0.00%
        chor_e         EX_chor_e   12.55        10  1.71%
          cl_e           EX_cl_e  0.2019         0  0.00%
     cobalt2_e      EX_cobalt2_e 0.00388         0  0.00%
         cu2_e          EX_cu2_e 0.02751         0  0.00%
         fe2_e          EX_fe2_e  0.2605         0  0.00%
         fe3_e          EX_fe3_e  0.3029         0  0.00%
         fru_e          EX_fru_e     500         6 40.94%
         gam_e          EX_gam_e   7.759         6  0.64%
      glc__D_e       EX_glc__D_e      20         6  1.64%
       glcur_e        EX_glcur_e   450.3         6 36.87%
      glu__L_e       EX_glu__L_e   38.74         5  2.64%
         gly_e          EX_gly_e   10.09         2  0.28%
      glygln_e       EX_glygln_e   10.23         7  0.98%
      glymet_e       EX_glymet_e   5.971         7  0.57%
         gua_e          EX_gua_e   9.436         5  0.64%
      hishis_e       EX_hishis_e   1.838        12  0.30%
      ile__L_e       EX_ile__L_e   11.27         6  0.92%
      indole_e       EX_indole_e   2.205         8  0.24%
           k_e            EX_k_e   7.573         0  0.00%
      leu__L_e       EX_leu__L_e   17.48         6  1.43%
      lys__L_e       EX_lys__L_e   13.31         6  1.09%
         mg2_e          EX_mg2_e  0.3366         0  0.00%
         mn2_e          EX_mn2_e 0.02681         0  0.00%
         nmn_e          EX_nmn_e 0.08838        11  0.01%
         no2_e          EX_no2_e      49         0  0.00%
         no3_e          EX_no3_e   131.1         0  0.00%
          o2_e           EX_o2_e   62.27         0  0.00%
          pi_e           EX_pi_e   38.17         0  0.00%
     pnto__R_e      EX_pnto__R_e 0.02235         9  0.00%
      pro__L_e       EX_pro__L_e   8.576         5  0.59%
           s_e            EX_s_e   3.584         0  0.00%
         so4_e          EX_so4_e  0.1683         0  0.00%
        sucr_e         EX_sucr_e   26.49        12  4.34%
         ura_e          EX_ura_e   12.83         4  0.70%
        urea_e         EX_urea_e   4.674         1  0.06%
      val__L_e       EX_val__L_e   16.42         5  1.12%
         zn2_e          EX_zn2_e 0.01323         0  0.00%

Secretion
---------
Metabolite    Reaction      Flux  C-Number C-Flux
     co2_e    EX_co2_e     -1000         1 17.63%
    etoh_e   EX_etoh_e    -528.9         2 18.65%
     for_e    EX_for_e    -912.4         1 16.09%
  glyclt_e EX_glyclt_e  -0.02595         2  0.00%
     h2o_e    EX_h2o_e    -252.7         0  0.00%
   inost_e  EX_inost_e    -450.3         6 47.63%
     nh4_e    EX_nh4_e      -122         0  0.00%
    4hba_c sink_4hba_c -0.008652         7  0.00%

We can see that still some of the substrates uptake a very high flux. You can play around modifying the uptake rate of specific reactions
by constraining the bounds of such reaction(s) and see the change in the growth rate

In [18]:
#Let's decrease the maximum uptake and production rate of all exchange reactions ('EX_metabolite_e') to constraint the solution space
for reaction in model_halop.reactions:
    if 'EX_' in reaction.id:
        reaction.bounds=(-10, 10) #Allow a maximum of 10 mmol gDW-1 h-1 of uptake or secretion
print(model_halop.optimize()) #Maximize growth rate under the new constraints
print(model_halop.summary()) #inspect the new uptake and secretion rates of extracellular metabolites

<Solution 2.014 at 0x7e23051bd6a0>
Objective
=========
1.0 Growth = 2.0143066838633854

Uptake
------
    Metabolite          Reaction      Flux  C-Number C-Flux
       5mcsn_e        EX_5mcsn_e        10         5  4.23%
LalaDgluMdap_e EX_LalaDgluMdap_e    0.2014        15  0.26%
        abg4_e         EX_abg4_e  0.001348        12  0.00%
         ade_e          EX_ade_e    0.4115         5  0.17%
      arg__L_e       EX_arg__L_e    0.5958         6  0.30%
      asn__L_e       EX_asn__L_e        10         4  3.39%
          bz_e           EX_bz_e 0.0002014         7  0.00%
         ca2_e          EX_ca2_e   0.01048         0  0.00%
        chol_e         EX_chol_e     5.021         5  2.13%
        chor_e         EX_chor_e    0.2782        10  0.24%
          cl_e           EX_cl_e   0.01048         0  0.00%
     cobalt2_e      EX_cobalt2_e 0.0002014         0  0.00%
         csn_e          EX_csn_e     2.886         4  0.98%
         cu2_e          EX_cu2_e  0.001428         0  0.00%
        fald_e         EX_fald_e        10         1  0.85%
         fe2_e          EX_fe2_e   0.01353         0  0.00%
         fe3_e          EX_fe3_e   0.01573         0  0.00%
         fru_e          EX_fru_e        10         6  5.08%
        g3pg_e         EX_g3pg_e     2.074         6  1.05%
        g3ps_e         EX_g3ps_e        10         6  5.08%
         gam_e          EX_gam_e      1.45         6  0.74%
      glc__D_e       EX_glc__D_e        10         6  5.08%
       glcur_e        EX_glcur_e        10         6  5.08%
         gly_e          EX_gly_e     0.497         2  0.08%
        glyc_e         EX_glyc_e        10         3  2.54%
      glymet_e       EX_glymet_e      0.31         7  0.18%
      glyphe_e       EX_glyphe_e    0.3732        11  0.35%
       gthrd_e        EX_gthrd_e        10        10  8.47%
         gua_e          EX_gua_e    0.4899         5  0.21%
          h2_e           EX_h2_e        10         0  0.00%
        h2o2_e         EX_h2o2_e        10         0  0.00%
           h_e            EX_h_e        10         0  0.00%
      hishis_e       EX_hishis_e   0.09542        12  0.10%
      ile__L_e       EX_ile__L_e    0.5852         6  0.30%
      indole_e       EX_indole_e    0.1145         8  0.08%
           k_e            EX_k_e    0.3932         0  0.00%
      leu__L_e       EX_leu__L_e    0.9075         6  0.46%
      lys__L_e       EX_lys__L_e    0.6912         6  0.35%
         mg2_e          EX_mg2_e   0.01747         0  0.00%
         mn2_e          EX_mn2_e  0.001392         0  0.00%
         nmn_e          EX_nmn_e  0.004589        11  0.00%
         no3_e          EX_no3_e         5         0  0.00%
          o2_e           EX_o2_e        10         0  0.00%
     pnto__R_e      EX_pnto__R_e   0.00116         9  0.00%
      pro__L_e       EX_pro__L_e      3.08         5  1.30%
       ptsla_e        EX_ptsla_e    0.5735        18  0.87%
           s_e            EX_s_e        10         0  0.00%
         so4_e          EX_so4_e  0.008738         0  0.00%
         tet_e          EX_tet_e         5         0  0.00%
         tre_e          EX_tre_e     3.402        12  3.46%
      udcpdp_e       EX_udcpdp_e        10        55 46.57%
        urea_e         EX_urea_e    0.2428         1  0.02%
         zn2_e          EX_zn2_e 0.0006869         0  0.00%

Secretion
---------
Metabolite    Reaction       Flux  C-Number C-Flux
   acald_e  EX_acald_e        -10         2  1.83%
  asp__L_e EX_asp__L_e        -10         4  3.65%
    cgly_e   EX_cgly_e        -10         5  4.57%
     co2_e    EX_co2_e        -10         1  0.91%
  cys__L_e EX_cys__L_e     -9.814         3  2.69%
    etoh_e   EX_etoh_e        -10         2  1.83%
     for_e    EX_for_e        -10         1  0.91%
     gal_e    EX_gal_e        -10         6  5.48%
    glcn_e   EX_glcn_e     -6.803         6  3.73%
  glu__L_e EX_glu__L_e        -10         5  4.57%
    glyb_e   EX_glyb_e     -5.021         5  2.29%
  glyc3p_e EX_glyc3p_e        -10         3  2.74%
  glyclt_e EX_glyclt_e     -0.255         2  0.05%
     h2o_e    EX_h2o_e        -10         0  0.00%
   inost_e  EX_inost_e        -10         6  5.48%
    meoh_e   EX_meoh_e        -10         1  0.91%
     nh4_e    EX_nh4_e        -10         0  0.00%
     no2_e    EX_no2_e         -5         0  0.00%
      pi_e     EX_pi_e        -10         0  0.00%
    ppap_e   EX_ppap_e   -0.09242         3  0.03%
  ser__L_e EX_ser__L_e        -10         3  2.74%
    thym_e   EX_thym_e        -10         5  4.57%
    tsul_e   EX_tsul_e        -10         0  0.00%
   udcpp_e  EX_udcpp_e        -10        55 50.23%
     ura_e    EX_ura_e     -2.219         4  0.81%
    4hba_c sink_4hba_c -0.0004492         7  0.00%

Imagine we have experimental evidence of the metabolites consumed and produced by Halopseudomonas. We know that our species does not produce methanol and neither consumes h2, so we can simulate that by knocking out those specific exchange reactions

In [19]:
model_halop.reactions.EX_meoh_e.knock_out()
model_halop.reactions.EX_h2_e.knock_out()
print(model_halop.optimize())
print(model_halop.summary())

<Solution 1.946 at 0x7e23051f9b50>
Objective
=========
1.0 Growth = 1.9464087057557218

Uptake
------
    Metabolite          Reaction      Flux  C-Number C-Flux
       5mcsn_e        EX_5mcsn_e     2.788         5  1.22%
LalaDgluMdap_e EX_LalaDgluMdap_e    0.1946        15  0.26%
        abg4_e         EX_abg4_e  0.001302        12  0.00%
         ade_e          EX_ade_e    0.3976         5  0.17%
      arg__L_e       EX_arg__L_e    0.5757         6  0.30%
      asn__L_e       EX_asn__L_e        10         4  3.51%
          bz_e           EX_bz_e 0.0001946         7  0.00%
         ca2_e          EX_ca2_e   0.01013         0  0.00%
        chol_e         EX_chol_e     5.413         5  2.38%
        chor_e         EX_chor_e    0.2688        10  0.24%
          cl_e           EX_cl_e   0.01013         0  0.00%
     cobalt2_e      EX_cobalt2_e 0.0001946         0  0.00%
         csn_e          EX_csn_e        10         4  3.51%
         cu2_e          EX_cu2_e   0.00138         0  0.00%
         fe2_e          EX_fe2_e   0.01307         0  0.00%
         fe3_e          EX_fe3_e    0.0152         0  0.00%
         fru_e          EX_fru_e        10         6  5.27%
        g3pg_e         EX_g3pg_e     2.004         6  1.06%
        g3ps_e         EX_g3ps_e        10         6  5.27%
         gam_e          EX_gam_e     1.401         6  0.74%
      glc__D_e       EX_glc__D_e        10         6  5.27%
       glcur_e        EX_glcur_e        10         6  5.27%
         gly_e          EX_gly_e    0.4803         2  0.08%
        glyc_e         EX_glyc_e        10         3  2.63%
      glymet_e       EX_glymet_e    0.2996         7  0.18%
      glyphe_e       EX_glyphe_e    0.3606        11  0.35%
       gthrd_e        EX_gthrd_e        10        10  8.78%
         gua_e          EX_gua_e    0.4734         5  0.21%
        h2o2_e         EX_h2o2_e        10         0  0.00%
           h_e            EX_h_e        10         0  0.00%
      hishis_e       EX_hishis_e    0.0922        12  0.10%
      ile__L_e       EX_ile__L_e    0.5655         6  0.30%
      indole_e       EX_indole_e    0.1106         8  0.08%
           k_e            EX_k_e    0.3799         0  0.00%
      leu__L_e       EX_leu__L_e    0.8769         6  0.46%
      lys__L_e       EX_lys__L_e    0.6679         6  0.35%
         mg2_e          EX_mg2_e   0.01689         0  0.00%
         mn2_e          EX_mn2_e  0.001345         0  0.00%
         nmn_e          EX_nmn_e  0.004434        11  0.00%
          o2_e           EX_o2_e        10         0  0.00%
     pnto__R_e      EX_pnto__R_e  0.001121         9  0.00%
      pro__L_e       EX_pro__L_e     2.976         5  1.31%
       ptsla_e        EX_ptsla_e    0.5542        18  0.88%
           s_e            EX_s_e        10         0  0.00%
         so4_e          EX_so4_e  0.008444         0  0.00%
         tet_e          EX_tet_e         5         0  0.00%
         tre_e          EX_tre_e     1.489        12  1.57%
      udcpdp_e       EX_udcpdp_e        10        55 48.26%
        urea_e         EX_urea_e    0.2346         1  0.02%
         zn2_e          EX_zn2_e 0.0006637         0  0.00%

Secretion
---------
Metabolite    Reaction      Flux  C-Number C-Flux
   acald_e  EX_acald_e       -10         2  1.89%
  asp__L_e EX_asp__L_e       -10         4  3.79%
    cgly_e   EX_cgly_e       -10         5  4.73%
     co2_e    EX_co2_e       -10         1  0.95%
  cys__L_e EX_cys__L_e     -9.82         3  2.79%
    etoh_e   EX_etoh_e       -10         2  1.89%
     for_e    EX_for_e       -10         1  0.95%
     gal_e    EX_gal_e       -10         6  5.68%
    glcn_e   EX_glcn_e    -2.978         6  1.69%
  glu__L_e EX_glu__L_e       -10         5  4.73%
    glyb_e   EX_glyb_e    -5.413         5  2.56%
  glyc3p_e EX_glyc3p_e       -10         3  2.84%
  glyclt_e EX_glyclt_e   -0.2464         2  0.05%
     h2o_e    EX_h2o_e       -10         0  0.00%
   inost_e  EX_inost_e       -10         6  5.68%
     nh4_e    EX_nh4_e       -10         0  0.00%
      pi_e     EX_pi_e       -10         0  0.00%
    ppap_e   EX_ppap_e  -0.08931         3  0.03%
  ser__L_e EX_ser__L_e       -10         3  2.84%
    thym_e   EX_thym_e    -2.788         5  1.32%
    tsul_e   EX_tsul_e       -10         0  0.00%
   udcpp_e  EX_udcpp_e       -10        55 52.06%
     ura_e    EX_ura_e    -9.356         4  3.54%
    4hba_c sink_4hba_c -0.000434         7  0.00%

The same can occur with genes, we can knock out specific genes, and those will force the knock out of the reactions catalyzed by those genes

In [20]:
print(model_halop.reactions.PGI.genes) #Check the gene of PGI reaction
print(model_halop.genes.FOUD01000020_1_13.reactions) #Reactions in which this gene is involved
model_halop.genes.FOUD01000020_1_13.knock_out() #Knock out that gene
print(model_halop.optimize()) #Check again if growth is affected

frozenset({<Gene FOUD01000020_1_13 at 0x7e230682b9b0>})
frozenset({<Reaction G6PI at 0x7e23060b2f90>, <Reaction G6PI3 at 0x7e23060b3050>, <Reaction PGI at 0x7e23059ca8d0>})
<Solution 1.946 at 0x7e23051e2120>